### ISSUE TITLE
Preserve order of Pipfile

### ISSUE THREAD

**Issue by timofurrer** [kennethreitz/pipenv#108]
Every time the Pipfile is changed the Pipfile section arrangement might, too. Which is a pain if you have to review such changes. Especially if it's the case for Pipfile and Pipfile.lock.

I'm not very familiar with TOML and the Python package used but maybe it's possible to preserve the order when writing to the Pipfile? (Using OrderedDicts internally or something).

-------------------

### TODO (this section by Kenneth Reitz)

- [x] determine if TOML library supports dumping OrderedDicts. 
- [x] determine if TOML library supports loading OrderedDicts. 
- [ ] implement preserve order in `Pipfile`
- [ ] implement preserve order in `Pipfile.lock`

**Comment by kennethreitz** [comment]
I will have to investigate ordering of the lockfile and, most likely, the order of the resulting `requirements.txt`.

**Comment by kennethreitz** [comment]
`toml.dumps()` supports ordered dicts. Loading is another issue.

**Comment by kennethreitz** [comment]
It does support ordered dicts for loading! 

```
print toml.loads(toml.dumps(d), _dict=OrderedDict)

**Comment by timofurrer** [comment]
I've just seen it, too ;)

**Comment by kennethreitz** [comment]
Go for it! I'm about to hop in a meeting :)

**Comment by kennethreitz** [comment]
working on it

**Comment by timofurrer** [comment]
I was just doing the PR. Nevermind ;)

**Comment by kennethreitz** [comment]
partially implemented

**Comment by nateprewitt** [comment]
From some initial tests, this looks to be working with #115. A second pair of eyes confirming this would be helpful :)

**Comment by timofurrer** [comment]
It appears that in same cases (most likely random) it still changes the order of `[packages]` and `[dev-packages]` section. However the order within the section is indeed preserved. 

As well as we might extend this issue to preserve the order of the lock file as well.

**Comment by kennethreitz** [comment]
we've done the best we can for now.
